from collections import deque

from sage.all import *

from bowman.comb_equiv import gen_comb_equivs
from bowman.geom_equiv import gen_geom_equiv
from bowman.fund_dom import FundDom


def sigma(mat):
    [[a, b], [c, d]] = mat
    return sage.all.matrix([[a, -b], [-c, d]])


def get_veech_equivs(ri, rj):
    ti, tj = ri.triangulation, rj.triangulation
    ces_ij = gen_comb_equivs(ti, tj)
    return list(filter(lambda x: x is not None,
                       (gen_geom_equiv(ti, tj, ce) for ce in ces_ij)))


def generators_veech(trin):
    """
    Find a generating set for the Veech group of trin
    :param trin:
    :rtype: MatrixGroup
    :return: MatrixGroup generated by the generators found
    """
    if not trin.is_delaunay():
        raise ValueError("Need to start with Delaunay Triangulation")
    r0 = trin.idr
    if r0.is_trivial:
        raise ValueError("The starting IDR is degenerate")

    self_equivs = get_veech_equivs(r0, r0)
    if len(self_equivs) > 2:
        raise ValueError("Starting IDR has self-equivalences", self_equivs)

    edges_crossed = set()
    edges_zipped = {}
    idrs_to_visit = deque([r0])
    fund_dom = [r0]
    gens = []
    codes_to_idrs = {r0.triangulation.code_comb: [r0]}

    while idrs_to_visit:
        idr_curr = idrs_to_visit.pop()
        for idx, edge in enumerate(idr_curr.polygon.edges):
            if edge not in edges_crossed and edge not in edges_zipped:
                edges_crossed |= {edge, edge.reverse()}
                idr_neighbor = idr_curr.cross_segment(idx)

                self_equivs = get_veech_equivs(idr_neighbor, idr_neighbor)
                if len(self_equivs) > 2:
                    raise ValueError("Neighbor IDR has self-equivalences")

                code_neighbor = idr_neighbor.triangulation.code_comb
                if code_neighbor not in codes_to_idrs:
                    codes_to_idrs[code_neighbor] = [idr_neighbor]
                    fund_dom.append(idr_neighbor)
                    idrs_to_visit.appendleft(idr_neighbor)
                else:
                    ves = [ve for idr in codes_to_idrs[code_neighbor]
                           for ve in get_veech_equivs(idr_neighbor, idr)]
                    if ves:
                        m = sigma(ves[0])
                        edge_opp = edge.apply_mobius(m)
                        edges_zipped[edge] = edge_opp
                        edges_zipped[edge_opp] = edge
                        edges_zipped[edge.reverse()] = edge_opp.reverse()
                        edges_zipped[edge_opp.reverse()] = edge.reverse()
                        gens.append(m)
                    else:
                        codes_to_idrs[code_neighbor].append(idr_neighbor)
                        fund_dom.append(idr_neighbor)
                        idrs_to_visit.appendleft(idr_neighbor)

    return FundDom(fund_dom, gens, edges_zipped)
